all:
  hosts:
    home-main:
      ansible_host: "" # FILL OUT
      ansible_port: 22 # FILL OUT
      ansible_user: "" # FILL OUT
      ansible_sudo_pass: "" # FILL OUT
    # adding multiple hosts wont play well with the group_vars file probably with the current setup
    # So use the below as just an example
    # home-throwaway:
    #   ansible_host: 192.168.178.3
    #   ansible_port: 2002
    #   ansible_user: kimi450
    #   ansible_sudo_pass: i_HaVe_A_gOoD_pAsSwOrD+123!
