---
- name: Install kubernetes using kubeadm
  hosts: all
  gather_facts: true
  tasks:
    - name: kubeadm installation
      environment:
        CONTAINERD_VERSION: "{{ kubeadm.versions.containerd }}"
        KUBERNETES_VERSION: "{{ kubeadm.versions.kubernetes }}"
        KUBERNETES_RELEASE_VERSION: "{{ kubeadm.versions.kubernetes_release }}"
        CRICTL_VERSION: "{{ kubeadm.versions.crictl }}"
      block:
        - name: copy over bootstrap script
          ansible.builtin.copy:
            src: ./kubeadm-cp.bash
            dest: "{{ basics.home_dir }}"
            owner: "{{ uid }}"
            group: "{{ uid }}"
            mode: '0777'
            backup: yes

        - name: bootstrap control plane node
          shell: >-
            {{ basics.home_dir }}/kubeadm-cp.bash -v 
            -t controlplane 
            -c {{ kubeadm.controlplane.count }}
            -h home-main
            -u {{ ansible_user }}
            -s {{ ansible_sudo_pass }}
          become: true


        - name: bootstrap control plane node
          shell: >-
            {{ basics.home_dir }}/kubeadm-cp.bash -v 
            -t worker 
            -c {{ kubeadm.worker.count }}
            -h home-main
            -u {{ ansible_user }}
            -s {{ ansible_sudo_pass }}
          become: true
