---
- import_playbook: install-kubernetes-kubespray.yaml
  when:
    - kubespray.enabled
    - not kubeadm.enabled

- import_playbook: install-kubernetes-kubeadm.yaml
  when:
    - not kubespray.enabled
    - kubeadm.enabled

- name: Install kubernetes using kubeadm
  hosts: all
  gather_facts: true
  tasks:
    - name: Install kubectl
      # https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
      block:
      - name: download binary
        become: true
        shell: "curl -LO \"https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl\""

      - name: install binary
        become: true
        shell: "install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl"

    - name: Install Helm
      # https://helm.sh/docs/intro/install/
      shell: "curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash"
      become: true

    - name: apply metrics server
      shell: kubectl apply -f https://raw.githubusercontent.com/pythianarora/total-practice/master/sample-kubernetes-code/metrics-server.yaml
