---
# https://github.com/kubernetes-sigs/kubespray/blob/master/docs/ansible/ansible.md
# https://github.com/kubernetes-sigs/kubespray/blob/master/docs/getting_started/getting-started.md
- name: Install kubernetes using kubespray
  hosts: all
  gather_facts: true
  tasks:
    - name: kubespray installation
      delegate_to: localhost
      block:
        - name: Clone kuberspray from github
          include_tasks: tasks-clone-git-repo.yaml
          vars:
            repo_dir: "{{ kubespray_repo_dir }}"
            repo_link: https://github.com/kubernetes-sigs/kubespray.git

        - name: "Checkout release branch: {{ kubespray.release }}"
          shell: "cd {{ kubespray_repo_dir }} && git checkout {{ kubespray.release }}"

        - name: setup config
          block:
            - name: setup inventory.ini
              block:
              - name: generate inventories entry
                set_fact:
                  inventory_entries: >
                    {{- inventory_entries | default('')
                        + item + ' etcd_member_name='  + '"' + 'etcd' +  my_idx|string + '"'
                        + ' ansible_host=' + '"' + hostvars[item].ansible_host + '"'
                        + ' ansible_port=' + '"' + hostvars[item].ansible_port|string + '"'
                        + ' ansible_user=' + '"' + hostvars[item].ansible_user + '"'
                        + ' ansible_sudo_pass=' + '"' + hostvars[item].ansible_sudo_pass + '"'
                    -}}
                loop: "{{ query('inventory_hostnames', 'all') }}"
                loop_control:
                  index_var: my_idx

              - name: populate inventory file
                copy:
                  dest: "{{ kubespray_inventory_ini }}"
                  content: |
                    [all:vars]
                    ansible_connection=ssh
                    ansible_become_user=root

                    [kube_control_plane]
                    {{ inventory_entries }}

                    [kube_node]
                    {{ inventory_entries }}

                    [etcd:children]
                    kube_control_plane
                    kube_node

            - name: setup addons
              block:
              - name: "update {{ kubespray_addons_yml }}"
                ansible.builtin.lineinfile:
                  path: "{{ kubespray_addons_yml }}"
                  regexp: "{{ item }}:.*"
                  line: "{{ item }}: true"
                loop: "{{ kubespray.addons }}"

              - name: "update {{ kubespray_k8s_cluster_yml }}"
                ansible.builtin.lineinfile:
                  path: "{{ kubespray_k8s_cluster_yml }}"
                  regexp: "^{{ item }}:.*"
                  line: "{{ item }}: true"
                loop: "{{ kubespray.k8s_cluster }}"

        - name: "run kubespray playbook (can take a long time): {{ kubespray.playbook }}"
          shell: |
            cd {{ kubespray_repo_dir }};
            python3 -m venv ..{{ kubespray_venv_dir }};
            . ..{{ kubespray_venv_dir }}/bin/activate;
            pip install -U -r requirements.txt;
            export ANSIBLE_CONFIG=../{{ kubespray_repo_dir }}/ansible.cfg;
            ansible-playbook -i ../{{ kubespray_inventory_ini }} ../{{ kubespray_repo_dir }}/{{ kubespray.playbook }} -b -v {{ kubespray.playbook_args }}

    - name: setup kubeconfig for user
      shell: |
        mkdir -p {{ basics.home_dir }}/.kube
        cp /etc/kubernetes/admin.conf {{ basics.home_dir }}/.kube/config
        chmod 777 -R {{ basics.home_dir }}/.kube
      become: true

    - name: Install kubectl
      # https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
      block:
      - name: download binary
        become: true
        shell: "curl -LO \"https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl\""

      - name: install binary
        become: true
        shell: "install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl"
      
    - name: Install Helm
      # https://helm.sh/docs/intro/install/
      shell: "curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash"
      become: true
  vars:
    kubespray_repo_dir: "./kubespray"
    kubespray_venv_dir: "{{ kubespray_repo_dir }}/kubespray-venv"
    kubespray_sample_dir: "{{ kubespray_repo_dir }}/inventory/sample"
    kubespray_inventory_ini: "{{ kubespray_sample_dir }}/inventory.ini"
    kubespray_addons_yml: "{{ kubespray_sample_dir }}/group_vars/k8s_cluster/addons.yml"
    kubespray_k8s_cluster_yml: "{{ kubespray_sample_dir }}/group_vars/k8s_cluster/k8s-cluster.yml"


