---
- name: Install and configure OpenThread Border Router
  hosts: all
  gather_facts: True
  tasks:
  - name: Native install
    # https://openthread.io/guides/border-router/build-native
    block:
    - name: install dependencies
      become: true
      apt:
        pkg: "{{ item }}"
        state: latest
      ignore_errors: yes
      loop:
        - git
        - tee

    - name: Setup Open Thread Border Router
      block:
        - name: Clone OTBR
          # https://openthread.io/guides/border-router/build-native
          shell: |
            rm -rf  {{ otbr_repo_dir }}
            git clone --depth=1 https://github.com/openthread/ot-br-posix {{ otbr_repo_dir }}
        - name: Setup OTBR
          # https://openthread.io/guides/border-router/build-native
          become: true
          shell: |
            cd {{ otbr_repo_dir }}
            ./script/bootstrap | tee {{ otbr_repo_dir }}/bootstrap-logs
            INFRA_IF_NAME={{ otbr.infra_if_name }} ./script/setup | tee {{ otbr_repo_dir }}/setup-logs

        - name: Setup OTBR web port to 8080
          become: true
          shell: |
            echo 'OTBR_WEB_OPTS="-I 0.0.0.0 -p 8080"' > /etc/default/otbr-web

        - name: "Patch config to use correct Radio Co-Processor (RCP) device from the default {{ default_rcp_location }}"
          become: true
          shell: |
            # create a rule to have the relevant device always created as /dev/ttyRCP
            ID_VENDOR=$(udevadm info -n {{ otbr.rcp_location }} | egrep -e 'ID_VENDOR_ID' | head | cut -d = -f 2)
            ID_MODEL=$(udevadm info -n {{ otbr.rcp_location }} | egrep -e 'ID_MODEL_ID' | head | cut -d = -f 2)
            ID_SERIAL=$(udevadm info -n {{ otbr.rcp_location }} | egrep -e 'ID_SERIAL_SHORT' | head | cut -d = -f 2)
            echo SUBSYSTEM==\"tty\", ATTRS{idVendor}==\"${ID_VENDOR}\", ATTRS{idProduct}==\"${ID_MODEL}\", ATTRS{serial}==\"${ID_SERIAL}\", SYMLINK+=\"ttyRCP\" > /etc/udev/rules.d/99-rcp.rules

            udevadm control --reload-rules
            udevadm trigger

            # make OTBR use /dev/ttyRCP
            sed -i s:{{ default_rcp_location }}:/dev/ttyRCP:g /etc/default/otbr-agent

        - name: Start OTBR services
          become: true
          shell: |
            {{ otbr_repo_dir }}/script/server | tee {{ otbr_repo_dir }}/server-logs

        - name: create network if one doesnt exist
          # https://openthread.io/guides/border-router/form-network
          # https://github.com/Kimi450/ubuntu-server/issues/44
          become: true
          shell: |
            EC=$(ot-ctl dataset | grep -q Network && echo 0 || echo 1)
            if [[ ${EC} -eq 0 ]]; then echo Dataset exists; exit 0; fi

            ot-ctl dataset init new
            ot-ctl dataset
            ot-ctl dataset commit active

        - name: check ifconfig
          shell: |
            ifconfig wpan0

        - name: Create config directory on hostpath for python-matter-server
          file:
            path: "{{ charts.services.configs_dir }}/matter-server"
            state: directory
            mode: '0777'
          become: true

        - name: run matter server as a stateful set
          # hostNetwork is true because HA and OTBR are on host network too
          shell: |
            kubectl apply -f - <<EOF
              apiVersion: apps/v1
              kind: StatefulSet
              metadata:
                name: matter-server
              spec:
                replicas: 1
                selector:
                  matchLabels:
                    app: matter-server
                template:
                  metadata:
                    labels:
                      app: matter-server
                  spec:
                    hostNetwork: true
                    dnsPolicy: ClusterFirstWithHostNet
                    containers:
                      - name: matter-server
                        image: ghcr.io/home-assistant-libs/python-matter-server:stable
                        ports:
                          - containerPort: 5580
                        volumeMounts:
                          - mountPath: /data
                            name: data
                    volumes:
                      - hostPath:
                          path: {{ charts.services.configs_dir }}/matter-server
                          type: ""
                        name: data
            EOF

    vars:
      otbr_repo_dir: "{{ basics.repos_dir }}/otbr"
      default_rcp_location: "/dev/ttyACM0"

