---
- name: Setup home server
  hosts: all
  gather_facts: false
  vars:
    vnc_display: 4
  tasks:
    #https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-vnc-on-ubuntu-18-04
    - name: Install tightvnc and ssh
      become: true
      apt:
        update_cache: yes
        pkg:
          - openssh-server
          - tightvncserver
          - xfce4 
          - xfce4-goodies

    - name: Backup old config
      command: mv /home/{{ ansible_user }}/.vnc/xstartup /home/{{ ansible_user }}/.vnc/xstartup.bak
      ignore_errors: True

    - name: Setup password
      expect:
        command: vncpasswd
        responses:
          Password: "{{ vnc_password }}"
          Verify: "{{ vnc_password }}"
          "Would you like to enter a view-only password (y/n)?": n

    - name: Copy over the new config
      copy:
        src: tightvnc-config/xstartup
        dest: /home/{{ ansible_user }}/.vnc/xstartup
        mode: "755"

    - name: Copy over the service file for systemd
      become: true
      copy:
        src: tightvnc-config/vncserver@.service
        dest: /etc/systemd/system/vncserver@.service

    - name: Reload systemd service
      include_tasks: tasks-reload-systemd-service.yaml
      vars:
        service_name: "vncserver@{{ vnc_display }}.service"
        become: True

    - include_tasks: tasks-allow-ports.yaml # should already work
      vars:
        ports: 
          - "ssh"
          - "590{{ vnc_display }}"
