---
- name: Setup home server
  hosts: all
  gather_facts: false
  tasks:
    - name: Get User ID (UID)
      shell: "id -u `whoami`"
      register: uid_output

    - name: Set shared facts
      set_fact:
        uid: "{{ uid_output.stdout }}"

- import_playbook: server-basics.yaml
  when:
    - basics.enabled

- import_playbook: install-docker.yaml
  when:
    - docker.enabled

- import_playbook: install-services.yaml
  vars:
    ip: "{{ ansible_host }}"

- import_playbook: install-tightvnc-and-ssh.yaml
  when:
    - vnc.enabled

- import_playbook: install-and-configure-samba.yaml
  when:
    - smb.enabled

- import_playbook: install-and-configure-squid.yaml
  when:
    - squid.enabled

- import_playbook: install-and-configure-cloudflare-dns-updater-service.yaml
  when:
    - cloudflare.enabled

- import_playbook: install-and-configure-pinless-bluetooth-pairing.yaml
  when:
    - bluetooth.pinless.enabled

# Deprecated stuff

- import_playbook: deprecated_playbooks/spotify/install-and-configure-spotifyd.yaml
  when:
    - spotify.enabled
