---
- name: Setup home server
  hosts: all
  gather_facts: false
  remote_user: kimi450
  tasks:
    - name: Set shared facts
      set_fact:
        user: kimi450
        dir_home: /home/kimi450
        dir_data: /home/kimi450/data
        dir_data_movies: /home/kimi450/data/movies
        dir_data_shows: /home/kimi450/data/shows
        dir_data_games: /home/kimi450/data/games
        dir_repos: /home/kimi450/repos
        dir_minikube_mount: /minikube-host

    - name: Disable sleep
      # https://serverfault.com/questions/1045949/how-to-disable-suspend-on-ubuntu-20-04-systemd-via-cli
      become: True
      block:
        - name: Change the logind service config file
          blockinfile:
            path: /etc/systemd/logind.conf
            block: |
              HandleSuspendKey=ignore
              HandleHibernateKey=ignore
              HandleLidSwitch=ignore
              HandleLidSwitchExternalPower=ignore
              HandleLidSwitchDocked=ignore
 
        - name: Restart service
          shell: systemctl restart systemd-logind

        - name: Disable sleep in systemd
          # https://www.unixtutorial.org/disable-sleep-on-ubuntu-server/
          become: true
          shell: systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target

    - name: Upgrade the system
      become: true
      apt:
        update_cache: yes
        upgrade: yes

    - name: Ensure all basic dependencies are present
      become: true
      apt:
        update_cache: yes
        pkg:
          - git
          - curl
          - vim
          - python3
          - python3-pip
          - htop
          - lm-sensors
          - stress
          - vlc
          - jq
          - net-tools
          - speedtest-cli
          - w3m
          - fio # for disk tests
          - mesa-utils # for GPU tests
        state: latest

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - "{{ dir_data }}"
        - "{{ dir_repos }}"
        - "{{ dir_data_movies }}"
        - "{{ dir_data_shows }}"
        - "{{ dir_data_games }}"

    - name: Setup the bashrc file and the vimrc file
      block:
        - name: Clone useful_files from github
          include_tasks: tasks-clone-git-repo.yaml
          vars:
            repo_dir:  "{{ useful_files_repo_dir }}"
            repo_link:  https://github.com/Kimi450/useful_files.git

        - name: Transfer bashrc file
          copy:
            remote_src: True
            src: "{{ useful_files_repo_dir }}/.bashrc"
            dest: "{{ dir_home }}"

        - name: Transfer vimrc edit script
          copy:
            remote_src: True
            src: "{{ useful_files_repo_dir }}/vimmer.sh"
            dest: "{{ dir_home }}"
            mode: "0755"

        - name: Run vimrc edit script
          command: "{{ useful_files_repo_dir }}/vimmer.sh"

        - name: Run vimrc edit script for sudo
          become: true
          command: "{{ useful_files_repo_dir }}/vimmer.sh"
      vars:
        useful_files_repo_dir: "{{ dir_repos }}/useful_files"

- import_playbook: install-tightvnc-and-ssh.yaml

# Enable if needed
# - import_playbook: install-and-configure-pinless-bluetooth-pairing.yaml

- import_playbook: install-cn-basics.yaml

- import_playbook: install-and-configure-minikube.yaml
  vars:
    api_server_forwarded_port: "3001"

- import_playbook: install-charts.yaml

- import_playbook: install-and-configure-samba.yaml

- import_playbook: install-and-configure-cloudflare-dns-updater-service.yaml

# TODO get kubeconfig setup for remote access
# - import_playbook: remote-access-minikube.yaml
#   vars:
#     api_server_forwarded_port: "6969"
