- name: Apply HTTPRoute {{ service_namespace }}
  shell: |
    kubectl apply -f - <<EOF
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: {{ service_name }}-route
        namespace: {{ service_namespace }}
      spec:
        parentRefs:
        - name: {{ gateway_controller_name }}
          namespace: {{ namespace_gateway_controller }}
        hostnames:
        - {{ service_hostname }}
        rules:
        - backendRefs:
          - name: {{ service_name }}
            port: {{ service_port }}
            namespace: {{ service_namespace }}
          matches:
            - path:
                type: PathPrefix
                value: /
          timeouts:
            request: 120s
            backendRequest: 120s
    EOF
