---
- name: Install and configure spotifyd
  hosts: all
  gather_facts: false
  remote_user: kimi450
  vars:
    remote_user: kimi450
    repo_dir: /home/kimi450/repos/spotifyd
    systemd_file_location: /etc/systemd/user/
  vars_prompt:
    - name: username
      prompt: What is your Spotify username?
      private: no

    - name: password
      prompt: What is your Spotify password?

  tasks:
    # https://spotifyd.github.io/spotifyd/installation/Ubuntu.html#building-spotifyd
    - name: Required dependencies
      become: true
      apt:
        update_cache: yes
        pkg:
          - rustc 
          - cargo
          - libasound2-dev
          - libssl-dev
          - pkg-config
        state: latest

    - name: Delete spotifyd directory
      file:
        path: "{{ repo_dir }}"
        state: absent

    - name: Create spotifyd directory
      file:
        path: "{{ repo_dir }}"
        state: directory
        mode: '0755'

    - name: Clone repo
      git:
        repo: https://github.com/Spotifyd/spotifyd.git
        dest: "{{ repo_dir }}"

    - name: Build the project
      shell: "cd {{ repo_dir }} && cargo build --release"

    - name: Move the binaries
      become: true  
      command: "mv {{ repo_dir }}/target/release/spotifyd /usr/bin/spotifyd"
  
    - name: Move systemd service file
      become: true  
      command: "mv {{ repo_dir }}/contrib/spotifyd.service {{ systemd_file_location }}"

    - name: Add user login info
      become: true  
      lineinfile: 
        path: "{{ systemd_file_location }}spotifyd.service"
        regexp: '^ExecStart(.*)$' 
        line: 'ExecStart=/usr/bin/spotifyd --no-daemon -u {{ username }} -p {{ password }}'
        backrefs: yes

    - name: Enable service
      shell: systemctl --user enable spotifyd.service

    - name: Start service
      shell: systemctl --user start spotifyd.service

    - name: Give user audio permissions
      shell: "adduser {{ remote_user }} audio"
      become: true