---
- name: Install basic charts
  hosts: all
  gather_facts: true
  remote_user: kimi450
  vars:
    namespace_user: kimi450
    namespace_monitoring: monitoring
    grafana_port: "3000"
    grafana_admin_password: admin
  tasks:

    - name: Create namespaces namespace
      shell: "kubectl create namespace {{ item }}"
      ignore_errors: True
      with_items:
        - "{{ namespace_monitoring }}"
        - "{{ namespace_user }}"

    - name: Install grafana
      block:
      - name: Install the chart
        include_tasks: tasks-install-chart.yaml
        # https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
        vars:
          repo_name: prometheus-community
          repo_link: https://prometheus-community.github.io/helm-charts
          install_namespace: monitoring
          release_name: kube-prometheus-stack

      - name: Expose grafana service
        include_tasks: tasks-kubernetes-port-forward-service.yaml
        vars:
          release_name: kube-prometheus-stack
          service_name_part: grafana
          service_file_name: grafana.service
          service_file_location_base: /etc/systemd/system/
          service_script_file_location_base: /etc/
          service_script_file_name: grafana.conf
          service_namespace: monitoring
          service_container_port: 80

      - name: "Reset Grafana admin password to '{{ grafana_admin_password }}'"  
        shell: "kubectl exec -it -n {{ namespace_monitoring }} $(kubectl get pods -n {{ namespace_monitoring }} | grep grafana | awk '{print $1}') -c grafana -- grafana-cli admin reset-admin-password {{ grafana_admin_password }}"
      
      - debug:
          msg: "You can log into Grafana at {{ hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}:{{ grafana_port }} using admin/{{ grafana_admin_password }}"

      - include_tasks: tasks-allow-ports.yaml
        vars:
          ports: 
            - "{{ grafana_port }}"