---
- name: Install and configure Minikube
  hosts: all
  gather_facts: false
  remote_user: kimi450
  vars:
    service_file_location: /etc/systemd/system/minikube.service
    port_expose_file_location: /etc/minikube-apiserver-port-forward.conf
    dir_minikube_mount: /minikube-host
  tasks:
    - name: Install Minikube
      # https://minikube.sigs.k8s.io/docs/start/
      block:
      - name: Download minikube package
        shell:  curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb

      - name: Install minikube
        become: true
        shell:  dpkg -i minikube_latest_amd64.deb
      
      - name: Delete minikube package
        file:
          path: minikube_latest_amd64.deb
          state: absent

    - name: "Create reverse proxy script to expose the API server on 0.0.0.0:{{ host_post }}"
      block:
        - name: "Remove any old reverse proxy script"
          become: true
          file:
            path: "{{ port_expose_file_location }}"
            state: absent

        - name: "Create new reverse proxy script"
          become: true
          lineinfile:
            path: "{{ port_expose_file_location }}"
            line: "#!/bin/bash\nnohup kubectl proxy --address='0.0.0.0' --port={{ api_server_forwarded_port }} --accept-hosts='.*' > /dev/null 2>&1 &"
            mode: "0755"
            create: yes

    - name: Setup and enable systemd service
      block:
        - name: Copy over the service file for systemd
          become: true
          copy:
            src: minikube-config/minikube.service
            dest: "{{ service_file_location }}"

        - name: "Service file edit: Change start command"
          become: true  
          lineinfile: 
            path: "{{ service_file_location }}"
            regexp: '^ExecStart=(.*)$' 
            line: 'ExecStart=/usr/bin/minikube start --mount --mount-string "{{ dir_home }}:{{ dir_minikube_mount }}" --cpus="max" --memory="6000" --disk-size="50gb" --nodes=1'
            backrefs: yes

        - name: "Service file edit: Add reverse proxy script"
          become: true  
          lineinfile: 
            path: "{{ service_file_location }}"
            regexp: '^ExecStartPost=(.*)$' 
            line: "ExecStartPost={{ port_expose_file_location }}"
            backrefs: yes
        
        - name: Reload to see new unit file
          become: true
          shell: systemctl daemon-reload

        - name: Stop the service
          become: True
          shell: "systemctl stop minikube.service"
          ignore_errors: True

        - name: Start the service
          become: True
          shell: "systemctl start minikube.service"

        - name: Enable the service
          become: True
          shell: "systemctl enable minikube.service"

        - name: Minikube notes
          debug:
            msg: "Directory '{{ dir_home }}' mounted on the minikube container at '{{ dir_minikube_mount }}'. More info https://github.com/kubernetes/minikube/pull/8159"
        
    - name: Enable nginx ingress controller
      shell: minikube addons enable ingress
    
    - include_tasks: tasks-allow-ports.yaml
      vars:
        ports: 
          - "{{ api_server_forwarded_port }}"