---
- name: Remote access for minikube
  hosts: all
  gather_facts: true
  remote_user: kimi450
  vars:
    remote_user: kimi450
    temp_file_loc: /tmp/kubeconfig
  tasks:
    - name: Copy kubeconfig for edits
      copy:
        src: "/home/{{ remote_user }}/.kube/config"
        dest: "{{ temp_file_loc }}"
        remote_src: true

    - name: Change IP
      replace: 
        path: "{{ temp_file_loc }}"
        regexp: 'https://((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?):[0-9]{1,5}' # to check for IP address
        replace: "http://{{ hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}:{{ api_server_forwarded_port }}"

    # - name: Copy edited config file to calling client machine
    # - name: Merge?
      