---
- name: Setup home server
  hosts: all
  gather_facts: false
  remote_user: kimi450
  tasks:
    - name: Set shared facts
      set_fact:
        user: kimi450
        dir_home: /home/kimi450
        dir_torrents: /home/kimi450/torrents
        dir_repos: /home/kimi450/repos
        dir_minikube_mount: /minikube-host

    - name: Disable sleep
      # https://serverfault.com/questions/1045949/how-to-disable-suspend-on-ubuntu-20-04-systemd-via-cli
      become: True
      block:
        - name: Change the logind service config file
          blockinfile:
            path: /etc/systemd/logind.conf
            block: |
              HandleSuspendKey=ignore
              HandleHibernateKey=ignore
              HandleLidSwitch=ignore
              HandleLidSwitchExternalPower=ignore
              HandleLidSwitchDocked=ignore

        - name: Restart service
          shell: systemctl restart systemd-logind

        - name: Disable sleep in systemd
          # https://www.unixtutorial.org/disable-sleep-on-ubuntu-server/
          become: true
          shell: systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target

    - name: Upgrade the system
      become: true
      apt:
        update_cache: yes
        upgrade: yes

    - name: Ensure all basic dependencies are present
      become: true
      apt:
        update_cache: yes
        pkg:
          - git
          - curl
          - vim
          - python3
          - python3-pip
          - htop
          - lm-sensors
          - stress
          - vlc
          - speedtest-cli
        state: latest

    - name: Create directories
      become: true
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - "{{ dir_torrents }}"
        - "{{ dir_repos }}"

    - name: Transfer bashrc file
      copy:
        src: ../.bashrc
        dest: "{{ dir_home }}"

    - name: Transfer vim pimping script
      copy:
        src: ../vimmer.sh
        dest: "{{ dir_repos }}"
        mode: "0755"

    - name: Run vim pimping script
      command: "{{ dir_repos }}/vimmer.sh"

    - name: Run vim pimping script for sudo
      become: true
      command: "{{ dir_repos }}/vimmer.sh"

- import_playbook: install-tightvnc-and-ssh.yaml

- import_playbook: install-and-configure-pinless-bluetooth-pairing.yaml

- import_playbook: install-cn-basics.yaml

- import_playbook: install-and-configure-minikube.yaml
  vars:
    api_server_forwarded_port: "6969"

- import_playbook: install-charts.yaml

- import_playbook: install-and-configure-samba.yaml

# TODO get kubeconfig setup for remote access
# - import_playbook: remote-access-minikube.yaml
#   vars:
#     api_server_forwarded_port: "6969"
